<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Water Bill {{ $bill->bill_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        .muted { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
        th { background: #f3f3f3; }
        .totals td { font-weight: bold; }
        .badge { display: inline-block; padding: 2px 8px; border: 1px solid #999; }
    </style>
</head>
<body>
    <h1>IRCUB Water Utility Bill</h1>
    <p class="muted">Integrated Revenue Collection &amp; Utility Billing Platform</p>

    <p>
        <strong>Bill No:</strong> {{ $bill->bill_number }}<br>
        <strong>Period:</strong> {{ $bill->period }}<br>
        <strong>Status:</strong> <span class="badge">{{ $bill->status }}</span><br>
        <strong>Due date:</strong> {{ optional($bill->due_date)->toDateString() }}
    </p>

    <p>
        <strong>Customer:</strong> {{ $bill->payer?->full_name }} ({{ $bill->payer?->tin }})<br>
        <strong>Phone:</strong> {{ $bill->payer?->phone }}<br>
        <strong>Account:</strong> {{ $bill->waterAccount?->account_no }} /
        Meter {{ $bill->waterAccount?->meter_no }} ({{ $bill->waterAccount?->tariff_class }})
    </p>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Amount (USD)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Previous reading</td>
                <td>{{ number_format((float) $bill->previous_reading, 3) }} m³</td>
            </tr>
            <tr>
                <td>Current reading</td>
                <td>{{ number_format((float) $bill->current_reading, 3) }} m³</td>
            </tr>
            <tr>
                <td>Consumption</td>
                <td>{{ number_format((float) $bill->consumption, 3) }} m³</td>
            </tr>
            <tr>
                <td>Usage charge (tiered tariff)</td>
                <td>{{ number_format((float) $bill->tariff_amount, 2) }}</td>
            </tr>
            <tr>
                <td>Fixed charge</td>
                <td>{{ number_format((float) $bill->fixed_charge, 2) }}</td>
            </tr>
            <tr>
                <td>Arrears brought forward</td>
                <td>{{ number_format((float) $bill->arrears_brought_forward, 2) }}</td>
            </tr>
            <tr>
                <td>Payments applied this cycle</td>
                <td>-{{ number_format((float) $bill->payments_applied, 2) }}</td>
            </tr>
            <tr class="totals">
                <td>Total due</td>
                <td>{{ number_format((float) $bill->total_due, 2) }}</td>
            </tr>
        </tbody>
    </table>

    @if($bill->abnormal_flag)
        <p><strong>Exception:</strong> {{ $bill->abnormal_reason }}</p>
    @endif

    <p class="muted" style="margin-top:24px;">Generated by IRCUB mock billing service.</p>
</body>
</html>
